.github/workflows/CI.yaml
setup.py

Fixing the issue with the installation from the setup.py file.

installation fixed from setup.py

---

ufcc/__init__.py
ufcc/sampledata.py

Adding the GIRK coordinates and trajectories as Sample Data and including a brief compute report.
```python
from ufcc.sampledata import GIRK
print(GIRK.coordinates)  ## absolute path to the data/coordinates.gro file
print(GIRK.trajectory)  ## absolute path to the data/trajectory.xtc file
```

including sample data 

---

.gitignore
README.md
bin/ufcc
setup.py
ufcc/contacts.py

This PR implements a prototype of the command line version of the library ([issue #14](https://github.com/ProLint/ufcc/issues/14)) and the handling of the MDAnalysis warnings about the masses ([issue #11](https://github.com/ProLint/ufcc/issues/11)).

CLI prototype and warnings handling

---

ufcc/server/index.html
ufcc/server/server.py
ufcc/server/static/js/app.js

Implements a basic pie chart on the dashboard.

Pie chart app

---

bin/ufcc
ufcc/server/server.py

Integrates the server call to the CLI program, which allows, in the future, the server to be invoked via cli options. 

Server integration

---

bin/ufcc
ufcc/contacts.py
ufcc/server/server.py
ufcc/ufcc.py

This PR adds a few crucial additions to ufcc base classes, which improve performance, readability, and server integration.

Ufcc improvements

---

ufcc/contacts.py
ufcc/server/get_json.py
ufcc/server/index.html
ufcc/server/server.py
ufcc/server/static/js/app.js

This PR mergers #25 into the `server` branch and resolves all conflicts.
The ganttApp still only includes toy data. 

Resolves server and gantt branches merge conflicts

---

ufcc/server/get_json.py
ufcc/server/index.html
ufcc/server/server.py
ufcc/server/static/js/app.js

Implements and integrates a Gantt application. 
See #12 for more. 

Gantt app implementation

---

ufcc/contacts.py
ufcc/server/index.html
ufcc/server/server.py
ufcc/server/static/js/app.js

This PR implements a heatmap application to show lipid-residue contacts on a per-atom/bead basis. 
This is an important application as part of #12 

Implement a heatmap application to show residue-lipid distance array

---

ufcc/server/index.html
ufcc/server/server.py
ufcc/server/static/js/app.js
ufcc/server/static/js/mol.js

Integrates a 3D structure viewer to the dashboard, along with the backend code to server the structure files. 

Implement a structure viewer to the dashboard

---

ufcc/contacts.py
ufcc/server/index.html
ufcc/server/server.py
ufcc/server/static/js/app.js
ufcc/server/static/js/mol.js

Adds various improvements and optimizations to #12. 

Optimizations, styling and speed improvements 

---

bin/ufcc
ufcc/__init__.py
ufcc/config.ini
ufcc/contacts.py
ufcc/ufcc.py

Implementing the use of parameters in a config file to be used during the calculation of the contacts.

implementing config file

---

ufcc/interactive_sel.py

Making sure that the order of the selection groups in the interactive mode is always the same, so that it can be scriptable for the user.

implementing fixed order of selection groups.

---

ufcc/contacts.py

Fixing residue offset in export function

---

ufcc/__init__.py
ufcc/contacts.py
ufcc/sampledata.py
ufcc/server/server.py
ufcc/ufcc.py

fix index of residue index.

---

.vscode/settings.json
prolint2/contacts.py
prolint2/prolint2.py
prolint2/sampledata.py
prolint2/tests/test_contacts.py
prolint2/tests/test_prolint2.py
prolint2/tests/test_sampledata.py
setup.py

adding unittests

---

README.md
docs/index.rst
docs/source/intro.rst
docs/source/usage.rst
prolint2/prolint2.py
prolint2/tests/test_prolint2.py

Updating documentation.

---

ufcc/server/chord_utils.py
ufcc/server/index.html
ufcc/server/server.py
ufcc/server/static/js/app.js
ufcc/server/utils.py

This PR implements a new analysis and visualization method. 
Shared contacts are lipid-protein interactions formed by two residues interacting with the same lipid during the same time frame. This new analysis method calculates these shared contacts and rank orders them according to the total count. 
It also implements a new visualization method using a network graph to depict residues as nodes and their pairwise shared contacts as edges. Important addition to #12 

Implement a contact network application

---

prolint2/contacts.py

extending contacts

---

.gitignore
bin/prolint2
prolint2/core/contact_provider.py
prolint2/core/universe.py
prolint2/metrics/base.py
setup.py

89 fix the command line usage
